version: '3'

services:


  mongodb:
    image: mongo:4.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.stats().ok' | mongo --quiet"]
      interval: 5s
      timeout: 30s
      retries: 10

  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - "npm"
      - "run"
      - "watch:docker"
    volumes:
      - "./:/app"
      - "backend-build-data:/app/build/"
    environment:
      - "APP_ENVIRONMENT=local"
    ports:
      - "0.0.0.0:7550:7550"
    healthcheck:
      interval: 20s
      timeout: 200s
      retries: 10

volumes:
  backend-build-data:
  backend-node-modules-data:
  mongo-db: